DefaultContentLanguage = "es"

baseURL = "https://asur.dev"

theme = "amperage"

pygmentsUseClasses = true

[languages]
    [languages.es]
        contentDir = "content"
        languageName = "Espa√±ol"
        languageCode = "es"
        title = "Un blog by Asur üßê"
        description = "Bienvenid@ a mi blog, si te gusta el desarrollo web, el SEO, el open source y la tecnolog√≠a en general echa un vistazo, seguro que encuentras algo interesante!"
        weight = 1
    [languages.en]
        contentDir = "content/english"
        languageName = "English"
        languageCode = "en"
        title = "A blog by Asur üßê"
        description = "Welcome to my blog, if you like web development, SEO, open source and technology in general have a look, you may find something interesting!"
        weight = 2

[[languages.es.menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/asurbernardo"
    weight = 5
[[languages.es.menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/asurbernardo"
    weight = 10
[[languages.es.menu.main]]
    url = "https://asur.dev/uses"
    name = "Mis /uses"
    weight = 15
[[languages.es.menu.main]]
    url = "https://asur.dev/support"
    name = "Ap√≥yame"
    weight = 20

[[languages.en.menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/asurbernardo"
    weight = 5
[[languages.en.menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/asurbernardo"
    weight = 10
[[languages.en.menu.main]]
    url = "https://asur.dev/en/support"
    name = "Support me"
    weight = 15

[taxonomies]
    tag = "tags"

[params]
    copyright = "asur.dev"
    themeColor = "#333"

    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker", "amp-iframe", "amp-autocomplete"]

    adsensePublisher = "ca-pub-8268925024957381"
    autoAdsEnabled = true

    googleAnalytics = "UA-128498798-1"
    commentsEmbedUrl = "https://comments.asur.dev"

    facebookSite = "asur.dev"
    twitterSite = "@asurbernardo"
    socialProfiles = ["https://twitter.com/asurbernardo","https://www.linkedin.com/in/asur-bernardo/","https://github.com/asurbernardo","https://stackoverflow.com/users/4524353/asur"]

    alternatePageName = "asur.dev"
    organizationLogo = "/logo.png"
    organizationName = "Asur"

    publisherName = "Asur Bernardo"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "blackfriday"

[outputs]
    home = [ "HTML", "RSS", "SearchIndex"]

[outputFormats]
    [outputFormats.SearchIndex]
        mediaType= "application/json"
        baseName= "search"
        isPlainText= true
        notAlternative= true